name: Linters

on:
  push:
    paths:
      - .github/workflows/linters.yml
      - flame/**
      - tests/**
      - setup.cfg
      - mypy.ini
    branches:
      - master
      - dev
  pull_request:
    paths:
      - .github/workflows/linters.yml
      - flame/**
      - tests/**
      - setup.cfg
      - mypy.ini
    branches:
      - master
      - dev

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Lint with flake8
        run: flake8

  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install isort
      - name: Check imports sorting with isort
        run: isort --check .

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mypy torchvision
      - name: Type check with mypy
        run: mypy flame
